spring.application.name=clientes-api
server.port=8080
spring.datasource.url=jdbc:oracle:thin:@192.168.37.147:1521/AXISP
spring.datasource.username=porta
spring.datasource.password=a1x7i8s9
# Cambia 'oracle.jdbc.driver.OracleDriver' por:
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true